### ISSUE TITLE
Consider transformation while testing intersection

### ISSUE THREAD

**Issue by UI233** [UI233/RayTracer#4]
Plz consider the transformation of position and normal in `hit()` method.

To transform position simply call `transformation(pos)` is sufficient.

**However**, normal vector should be multiplied by **Matrix  `transpose(inverse(transformation))`**.
**Moreover**, you're supposed to set `normal.w` to 0 which avoids displacement of normal.

**Comment by logos-mhr** [comment]
Fixed.
